"""Render the two independent destination fences for the Tin-owned forward proxy."""

from __future__ import annotations

import argparse
import ipaddress
from pathlib import Path

# Conservatively exclude special-purpose space (including translation/tunnel
# prefixes). Public destinations may use only TCP 80/443. Keep this policy in
# both Squid and nftables: DNS names alone are not a rebinding defense.
BLOCKED_V4 = (
    "0.0.0.0/8",
    "10.0.0.0/8",
    "100.64.0.0/10",
    "127.0.0.0/8",
    "169.254.0.0/16",
    "172.16.0.0/12",
    "192.0.0.0/24",
    "192.0.2.0/24",
    "192.88.99.0/24",
    "192.168.0.0/16",
    "198.18.0.0/15",
    "198.51.100.0/24",
    "203.0.113.0/24",
    "224.0.0.0/4",
    "240.0.0.0/4",
)
BLOCKED_V6 = ("2001::/23", "2001:db8::/32", "2002::/16", "3fff::/20")


def resolvers(path: Path) -> tuple[str, ...]:
    values = []
    for line in path.read_text().splitlines():
        fields = line.split()
        if len(fields) >= 2 and fields[0] == "nameserver":
            values.append(str(ipaddress.ip_address(fields[1])))
    if not values:
        raise ValueError("the proxy needs at least one explicit DNS resolver")
    return tuple(dict.fromkeys(values))


def squid_config(static_ip: str, dns: tuple[str, ...]) -> str:
    address = str(ipaddress.IPv4Address(static_ip))
    blocked = " ".join((*BLOCKED_V4, address + "/32"))
    blocked6 = " ".join(BLOCKED_V6)
    tls = (
        "tls-cert=/etc/tin-lite-proxy/tls/fullchain.pem tls-key=/etc/tin-lite-proxy/tls/privkey.pem"
    )
    helper = "/usr/local/lib/tin-lite/proxy_grants.py /var/lib/tin-lite-proxy-grants"
    return f"""# Generated by Tin; no HTTP listener or TLS interception.
https_port 8888 {tls} tls-min-version=1.2
visible_hostname tin-lite-proxy
pid_filename /run/tin-lite-proxy/squid.pid
cache_effective_user proxy
cache_effective_group proxy
auth_param basic program /usr/bin/python3 {helper}
auth_param basic children 4
auth_param basic realm Tin run proxy
auth_param basic credentialsttl 1 seconds
acl run_grant proxy_auth REQUIRED
acl web_ports port 80 443
acl tls_port port 443
acl connect method CONNECT
acl blocked_v4 dst {blocked}
acl global_v6 dst 2000::/3
acl any_v6 dst ::/0
acl blocked_v6 dst {blocked6}
http_access deny manager
http_access deny !web_ports
http_access deny connect !tls_port
http_access deny to_localhost
http_access deny blocked_v4
http_access deny any_v6 !global_v6
http_access deny blocked_v6
http_access allow run_grant
http_access deny all
dns_nameservers {" ".join(dns)}
pinger_enable off
netdb_filename none
cache deny all
access_log none
cache_store_log none
cache_log /var/log/squid/cache.log
debug_options ALL,0
forwarded_for delete
via off
connect_timeout 10 seconds
request_timeout 30 seconds
read_timeout 5 minutes
client_lifetime 1 hour
shutdown_lifetime 1 seconds
"""


def nft_config(static_ip: str, uid: int, dns: tuple[str, ...]) -> str:
    address = str(ipaddress.IPv4Address(static_ip))
    if uid <= 0:
        raise ValueError("the proxy must use an unprivileged dedicated UID")
    dns_rules = []
    for resolver in dns:
        parsed = ipaddress.ip_address(resolver)
        family = "ip" if parsed.version == 4 else "ip6"
        dns_rules.append(f"        {family} daddr {parsed} udp dport 53 accept")
        dns_rules.append(f"        {family} daddr {parsed} tcp dport 53 accept")
    return f"""# Atomic replacement of our table only; never flush host firewall rules.
add table inet tin_lite_proxy
flush table inet tin_lite_proxy
table inet tin_lite_proxy {{
    set blocked_v4 {{
        type ipv4_addr
        flags interval
        auto-merge
        elements = {{ {", ".join((*BLOCKED_V4, address))} }}
    }}
    set blocked_v6 {{
        type ipv6_addr
        flags interval
        elements = {{ {", ".join(BLOCKED_V6)} }}
    }}
    chain output {{
        type filter hook output priority 0; policy accept;
        meta skuid {uid} jump proxy_egress
    }}
    chain proxy_egress {{
        # Replies to inbound proxy clients, never an outbound connection bypass.
        ct direction reply accept
{chr(10).join(dns_rules)}
        # Includes the VM's own globally addressed interfaces.
        oifname "lo" reject
        ip daddr @blocked_v4 reject
        ip6 daddr != 2000::/3 reject
        ip6 daddr @blocked_v6 reject
        tcp dport {{ 80, 443 }} accept
        reject
    }}
}}
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--static-ip", required=True)
    parser.add_argument("--uid", type=int, required=True)
    parser.add_argument("--resolv-conf", type=Path, default=Path("/etc/resolv.conf"))
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    dns = resolvers(args.resolv_conf)
    (args.output / "proxy.nft").write_text(nft_config(args.static_ip, args.uid, dns))
    (args.output / "squid.conf").write_text(squid_config(args.static_ip, dns))


if __name__ == "__main__":
    main()
